<?xml version="1.0"?>
<package format="3">
  <name>aurora_search</name>
  <version>0.1.0</version>
  <description>ROS-independent static 3D A* search for AURORA-Planner.</description>

  <maintainer email="pathalgo26@todo.todo">PathAlgo26</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>aurora_map</depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
