<?xml version="1.0"?>
<package format="3">
  <name>aurora_bringup</name>
  <version>0.1.0</version>
  <description>Launch files and baseline parameters for AURORA-Planner.</description>

  <maintainer email="pathalgo26@todo.todo">PathAlgo26</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>aurora_ros</exec_depend>
  <exec_depend>aurora_sim</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
