<?xml version="1.0"?>
<package format="3">
  <name>aurora_math</name>
  <version>0.1.0</version>
  <description>ROS-independent mathematical primitives for AURORA-Planner.</description>

  <maintainer email="pathalgo26@todo.todo">PathAlgo26</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>eigen3_cmake_module</depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
